//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoStockPortfolio
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_close_clear_cancel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_preferences = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int addPositionPrice = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int addPositionSaveButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int addPositionShares = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int addPositionTicker = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int btnAddPortfolio = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int btnAddPosition = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int btnSave = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int btnSaveConfig = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int configList = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int portfolioList = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int portfolioName = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int quoteHeaderLayout = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int quoteListview = 2131034124;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addportfolio = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int addposition = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int config = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int portfolio = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
